import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers";
import { getAuth, getToken } from "@/lib/auth-options";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getAuth();
  const token = getToken();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={session} token={token}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
